Add the `--dolphin-process-name` command-line option.
aldelaro5/dolphin-memory-engine pull request #105
Opened 2024-03-06 21:52 UTC by cristian64

Used to override the name of the Dolphin Emulator process that the DME will search for in the system while trying to hook.

The short version of the option is `-d`.

The [undocumented] `DME_DOLPHIN_PROCESS_NAME` environment variable can
be used alternatively.

Fixes #42.

This work also enables the `--version` and `--help` command-line arguments.

Bonus: Trailing spaces, as well as `\r` characters, have been removed.

2024-03-06 21:54 UTC, cristian64 commented
The first two commits are only whitespace changes. (I can move them to a separate PR if it makes things easier.)

The changes for Windows and macOS have been made blindly; unable to test. Let's see if the build succeeds.

2024-03-07 01:31 UTC, dreamsyntax commented
> Would you able to test at least on Windows? It'd be interesting to test also with non-ASCII characters, which I'm hoping it will work.

Tested with process name '攫'
![image](https://github.com/aldelaro5/dolphin-memory-engine/assets/14857235/24292649-e3d8-4374-b955-54d7c1b35d05)

Launching with no arg:
![image](https://github.com/aldelaro5/dolphin-memory-engine/assets/14857235/a3e73d47-143c-4873-bb89-21490bc1a3dd)

Launching with `--dolphin-process-name 攫` or `-d 攫`:
No luck, does not detect the process.

Launching with `--dolphin-process-name 攫.exe` or `-d 攫.exe`:
Attached properly.


Also tested with `ShadowSX` as name of Dolphin process. The results are the same.

--
Testing with no modification to `Dolphin.exe` also works as expected.

--
Can we implicitly add .exe to the search type of the user does not specify? Or do you think its standard to require it?

2024-03-07 01:33 UTC, dreamsyntax requested changes

2024-03-07 01:33 UTC, dreamsyntax commented on Source/main.cpp
> +  QApplication::setApplicationVersion("0.9.0");
Lets set this to 1.0.0 as that is the next release.

Please also add the help/args to the README file.

2024-03-07 06:08 UTC, cristian64 commented
> > Would you able to test at least on Windows? It'd be interesting to test also with non-ASCII characters, which I'm hoping it will work.
> 
> [...]
> 
> -- Can we implicitly add .exe to the search type of the user does not specify? Or do you think its standard to require it?

I think my preference is to be specific, but I'm having a hard time finding a case where the implicit extension could be a problem. So, happy to add it if you haven't changed your mind since your comment.

2024-03-07 06:24 UTC, dreamsyntax commented
> > > Would you able to test at least on Windows? It'd be interesting to test also with non-ASCII characters, which I'm hoping it will work.
> > 
> > 
> > [...]
> > -- Can we implicitly add .exe to the search type of the user does not specify? Or do you think its standard to require it?
> 
> I think my preference is to be specific, but I'm having a hard time finding a case where the implicit extension could be a problem. So, happy to add it if you haven't changed your mind since your comment.

I would think
-> check explicit, if not found and on windows assume .exe or something like that

2024-03-07 06:29 UTC, cristian64 commented
> > > > Would you able to test at least on Windows? It'd be interesting to test also with non-ASCII characters, which I'm hoping it will work.
> > > 
> > > 
> > > [...]
> > > -- Can we implicitly add .exe to the search type of the user does not specify? Or do you think its standard to require it?
> > 
> > 
> > I think my preference is to be specific, but I'm having a hard time finding a case where the implicit extension could be a problem. So, happy to add it if you haven't changed your mind since your comment.
> 
> I would think -> check explicit, if not found and on windows assume .exe or something like that
> 
> Or just make it clear in the help/readme that windows must include the extension. I'm fine with that too.

The option's help description does say the file extension must be given, but the Windows ecosystem is known for not minding.

2024-03-07 06:53 UTC, dreamsyntax approved these changes

2024-03-07 06:54 UTC, dreamsyntax commented
> > > > > Would you able to test at least on Windows? It'd be interesting to test also with non-ASCII characters, which I'm hoping it will work.
> > > > 
> > > > 
> > > > [...]
> > > > -- Can we implicitly add .exe to the search type of the user does not specify? Or do you think its standard to require it?
> > > 
> > > 
> > > I think my preference is to be specific, but I'm having a hard time finding a case where the implicit extension could be a problem. So, happy to add it if you haven't changed your mind since your comment.
> > 
> > 
> > I would think -> check explicit, if not found and on windows assume .exe or something like that
> > Or just make it clear in the help/readme that windows must include the extension. I'm fine with that too.
> 
> The option's help description does say the file extension must be given, but the Windows ecosystem is known for not minding.

Your call. I'm fine either way, merge when you think its good to go.
If you dont do this:
https://github.com/aldelaro5/dolphin-memory-engine/pull/105#discussion_r1515365623
I can just add it before release.

2024-03-07 20:15 UTC, cristian64 commented
I've made the tweak so that, on Windows, the `.exe` file extension can be omitted.

2024-03-07 21:50 UTC, dreamsyntax approved these changes
Tested with
`-d test`
and
`-d test.exe`

Both work as expected.

2024-03-07 21:50 UTC, merged